CREATE TABLE semantic_layer (
    id_type_file VARCHAR(5) NOT NULL,
    field_position INTEGER,
    field_name VARCHAR(255) NOT NULL,
    field_description VARCHAR(255),
    pk BOOLEAN,
    data_type VARCHAR(255),
    length VARCHAR(255),
    nullable BOOLEAN,
    decimal_symbol VARCHAR(255),
    referential_bbdd VARCHAR(255),
    referential_table_field_name VARCHAR(255),
    init_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_id_type_file FOREIGN KEY (id_type_file) REFERENCES file_configuration(id_type_file)
);

INSERT INTO semantic_layer (
  id_type_file,
  field_position,
  field_name,
  field_description,
  pk,
  data_type,
  length,
  nullable,
  decimal_symbol,
  referential_bbdd,
  referential_table_field_name,
  init_date
) VALUES
('00001', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00001', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00001', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00001', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00001', 8, 'idexcel', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 11, 'date_data', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 13, 'status', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 19, 'idbsi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 32, 'load_date', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00001', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00002', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00002', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00002', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00002', 8, 'idexcel', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 11, 'date_data', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 13, 'status', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 19, 'idbsi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 32, 'load_date', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00002', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00003', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00003', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00003', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00003', 8, 'idexcel', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 11, 'date_data', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 13, 'status', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 19, 'idbsi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 32, 'load_date', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00003', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00004', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00004', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00004', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00004', 8, 'idexcel', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 11, 'date_data', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 13, 'status', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 19, 'idbsi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 32, 'load_date', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00004', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00005', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00005', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00005', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00005', 8, 'idexcel', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 11, 'date_data', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 13, 'status', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 19, 'idbsi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 32, 'load_date', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00005', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00006', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00006', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00006', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00006', 8, 'idexcel', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 11, 'date_data', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 13, 'status', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 19, 'idbsi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 32, 'load_date', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00006', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00007', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00007', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00007', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00007', 8, 'idexcel', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 11, 'date_data', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 13, 'status', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 19, 'idbsi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 32, 'load_date', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00007', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00008', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00008', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00008', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00008', 8, 'idexcel', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 11, 'date_data', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 13, 'status', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 19, 'idbsi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 32, 'load_date', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00008', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00009', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00009', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00009', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00009', 8, 'idexcel', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 11, 'date_data', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 13, 'status', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 19, 'idbsi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 32, 'load_date', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00009', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00010', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00010', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00010', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00010', 8, 'idexcel', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 11, 'date_data', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 13, 'status', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 19, 'idbsi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 32, 'load_date', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00010', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00011', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00011', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00011', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00011', 8, 'idexcel', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 11, 'date_data', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 13, 'status', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 19, 'idbsi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 32, 'load_date', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00011', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00012', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00012', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00012', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00012', 8, 'idexcel', 'output field', false, 'DECIMAL(8,5)', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 11, 'date_data', 'output field', false, 'DATE', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 13, 'status', 'output field', false, 'INT', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 19, 'idbsi', 'output field', false, 'INT', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 32, 'load_date', 'output field', false, 'DATE', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00012', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00013', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00013', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00013', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00013', 8, 'idexcel', 'output field', false, 'DECIMAL(8,5)', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 11, 'date_data', 'output field', false, 'DATE', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 13, 'status', 'output field', false, 'INT', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 19, 'idbsi', 'output field', false, 'INT', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 32, 'load_date', 'output field', false, 'DATE', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00013', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00014', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00014', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00014', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00014', 8, 'idexcel', 'output field', false, 'DECIMAL(8,5)', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 11, 'date_data', 'output field', false, 'DATE', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 13, 'status', 'output field', false, 'INT', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 19, 'idbsi', 'output field', false, 'INT', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 32, 'load_date', 'output field', false, 'DATE', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00014', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00015', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00015', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00015', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00015', 8, 'idexcel', 'output field', false, 'DECIMAL(8,5)', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 11, 'date_data', 'output field', false, 'DATE', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 13, 'status', 'output field', false, 'INT', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 19, 'idbsi', 'output field', false, 'INT', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 32, 'load_date', 'output field', false, 'DATE', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00015', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00016', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00016', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00016', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00016', 8, 'idexcel', 'output field', false, 'DECIMAL(8,5)', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 11, 'date_data', 'output field', false, 'DATE', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 13, 'status', 'output field', false, 'INT', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 19, 'idbsi', 'output field', false, 'INT', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 32, 'load_date', 'output field', false, 'DATE', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00016', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00017', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00017', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00017', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00017', 8, 'idexcel', 'output field', false, 'DECIMAL(8,5)', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 11, 'date_data', 'output field', false, 'DATE', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 13, 'status', 'output field', false, 'INT', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 19, 'idbsi', 'output field', false, 'INT', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 32, 'load_date', 'output field', false, 'DATE', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00017', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 1, 'template_code', 'tipo de calculadora', false, 'STRING', 32, false, null, 'formacion', 'myschema_pablo.td_templates.template_code', CURRENT_TIMESTAMP),
('00018', 2, 'sheet', 'nombre de la pesta�a', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 3, 'data_type', 'tipo de dato', false, 'STRING', 32, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 4, 'excel_cell', 'celda donde se encuentra el dato', false, 'STRING', 4, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 5, 'column_x', 'columna donde se encuentra el dato en el DataFrame', false, 'STRING', 5, false, null, null, null, CURRENT_TIMESTAMP),
('00018', 6, 'row_y', 'fila donde se encuentra el dato en el DataFrame', false, 'DECIMAL(8,4)', 10, false, null, null, null, CURRENT_TIMESTAMP),
('00018', 7, 'data_name', 'nombre del dato para utilidad t�cnica', false, 'STRING', 32, false, null, null, null, CURRENT_TIMESTAMP),
('00018', 8, 'idexcel', 'output field', false, 'DECIMAL(8,5)', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 9, 'excname', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 10, 'coduni', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 11, 'date_data', 'output field', false, 'DATE', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 12, 'axis', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 13, 'status', 'output field', false, 'INT', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 14, 'idarea', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 15, 'idcurr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 16, 'idsover', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 17, 'idprod', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 18, 'idisco', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 19, 'idbsi', 'output field', false, 'INT', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 20, 'idsegm', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 21, 'idasli', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 22, 'idtmbuc', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 23, 'idscene', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 24, 'idencum', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 25, 'idisin', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 26, 'idmatur', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 27, 'idauxdi', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 28, 'auvame', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 29, 'curve', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 30, 'idmetr', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 31, 'version', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 32, 'load_date', 'output field', false, 'DATE', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 33, 'tip_act', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP),
('00018', 34, 'car_aux', 'output field', false, 'STRING', 255, true, null, null, null, CURRENT_TIMESTAMP);